### ISSUE TITLE
Issue when importing mediapipe

### ISSUE THREAD

**Issue by sandeeppvn** [cansik/mediapipe-silicon#8]
Hi,

When importing mediapipe on Mac ARM64, im facing the following issue:

`>>> 
import mediapipe as mp

objc[17608]: Class CaptureDelegate is implemented in both /Users/sandeeppvn/opt/miniconda3/envs/640/lib/python3.10/site-packages/mediapipe/.dylibs/libopencv_videoio.3.4.16.dylib (0x100d98860) and /Users/sandeeppvn/opt/miniconda3/envs/640/lib/python3.10/site-packages/cv2/cv2.abi3.so (0x16650e538). One of the two will be used. Which one is undefined.
objc[17608]: Class CVWindow is implemented in both /Users/sandeeppvn/opt/miniconda3/envs/640/lib/python3.10/site-packages/mediapipe/.dylibs/libopencv_highgui.3.4.16.dylib (0x1009d8a68) and /Users/sandeeppvn/opt/miniconda3/envs/640/lib/python3.10/site-packages/cv2/cv2.abi3.so (0x16650e588). One of the two will be used. Which one is undefined.
objc[17608]: Class CVView is implemented in both /Users/sandeeppvn/opt/miniconda3/envs/640/lib/python3.10/site-packages/mediapipe/.dylibs/libopencv_highgui.3.4.16.dylib (0x1009d8a90) and /Users/sandeeppvn/opt/miniconda3/envs/640/lib/python3.10/site-packages/cv2/cv2.abi3.so (0x16650e5b0). One of the two will be used. Which one is undefined.
objc[17608]: Class CVSlider is implemented in both /Users/sandeeppvn/opt/miniconda3/envs/640/lib/python3.10/site-packages/mediapipe/.dylibs/libopencv_highgui.3.4.16.dylib (0x1009d8ab8) and /Users/sandeeppvn/opt/miniconda3/envs/640/lib/python3.10/site-packages/cv2/cv2.abi3.so (0x16650e5d8). One of the two will be used. Which one is undefined.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sandeeppvn/opt/miniconda3/envs/640/lib/python3.10/site-packages/mediapipe/__init__.py", line 17, in <module>
    import mediapipe.python.solutions as solutions
  File "/Users/sandeeppvn/opt/miniconda3/envs/640/lib/python3.10/site-packages/mediapipe/python/solutions/__init__.py", line 17, in <module>
    import mediapipe.python.solutions.drawing_styles
  File "/Users/sandeeppvn/opt/miniconda3/envs/640/lib/python3.10/site-packages/mediapipe/python/solutions/drawing_styles.py", line 20, in <module>
    from mediapipe.python.solutions.drawing_utils import DrawingSpec
  File "/Users/sandeeppvn/opt/miniconda3/envs/640/lib/python3.10/site-packages/mediapipe/python/solutions/drawing_utils.py", line 25, in <module>
    from mediapipe.framework.formats import detection_pb2
  File "/Users/sandeeppvn/opt/miniconda3/envs/640/lib/python3.10/site-packages/mediapipe/framework/formats/detection_pb2.py", line 5, in <module>
    from google.protobuf.internal import builder as _builder
ImportError: cannot import name 'builder' from 'google.protobuf.internal' (/Users/sandeeppvn/opt/miniconda3/envs/640/lib/python3.10/site-packages/google/protobuf/internal/__init__.py)
`

My System details:
Mac Air M1 2020
macOS Ventura 13.0.1

Using Miniconda ARM64 Mac Version
Python 3.10.8

mediapipe-silicon: 0.8.11
protobuf: 3.19.0

Kindly help how to resolve this issue.

**Comment by mrezzaaa** [comment]
same problem, so minimal documentation. at least write 'How to use' this library

**Comment by cansik** [comment]
@sandeeppvn Could it be a problem with MacOS Ventura? I just tried it on MacOS Monterey (12.6) with conda and python 3.10 and the import worked. I currently did not update to Ventura and Github still does not support Actions to test on newer systems.

Otherwise, I just googled the error message `ImportError: cannot import name 'builder' from 'google.protobuf.internal'` and found the following thread: [stackoverflow/71759248](https://stackoverflow.com/questions/71759248/importerror-cannot-import-name-builder-from-google-protobuf-internal). To test this out, just uninstall `protobuf` and reinstall it with `pip install "protobuf>=3.11,<4"`.

@mrezzaaa This is a drop-in replacement library which does not change anything regarding the usage of [Mediapipe](https://google.github.io/mediapipe/).

**Comment by giorgiop** [comment]
I am experiencing the same issue.

**Comment by cansik** [comment]
@giorgiop Did you re-install the `protobuf` package as suggested?

**Comment by giorgiop** [comment]
```
MacBook Pro 16" 2021 with an Apple M1 Max CPU running macOS Ventura 13.0.1
python 3.10.8
protobuf 3.20.1
```

running on `homebrew/Caskroom/miniforge`

**Comment by cansik** [comment]
@giorgiop Thanks for the information. I am still not able to reproduce and I do not have the feeling this is a problem of `mediapipe-silicon`, because the issue itself occurs with many google packages as you can [read here](https://stackoverflow.com/a/47904556/1138326). And if you have protobuf installed with tensorflow, the builder.py is maybe missing as [described here](https://stackoverflow.com/a/73977034/1138326).

Could you please check if `protobuf` is correctly installed and that you can import the `builder.py`? You can check that by using the following command:

```bash
python -c "from google.protobuf.internal import builder; print('works')"
```

**Comment by satoooh** [comment]
Hi, I have the same problem.

Here is my environment:
- MacBook Pro 16inch, 2021 with Apple M1 Pro ( macOS Monterey v12.6)
- Python 3.10.5 (installed with pyenv)
- Poetry 1.3.2
- venv
- protobuf 3.20.3 (automatically installed when you try this command `poetry add mediapipe-silicon`)

```
python -m venv venv && source venv/bin/activate
poetry init
poetry add mediapipe-silicon
python -c "import mediapipe as mp"
```

And I tried this command `python -c "from google.protobuf.internal import builder; print('works')"`, it worked fine.

**Comment by satoooh** [comment]
I tried changing the package management tool from Poetry to pip, but the same problem occurred.

```
python -m venv venv && source venv/bin/activate
pip install mediapipe-silicon
python -c "import mediapipe as mp"
```

**Comment by cansik** [comment]
@satoooh Thank you for the information. Do you think it is a problem with Ventura? I am currently still on Monterey, so I can not really test it. Otherwise, could you check in the `site-packages`, if there is a `mediapipe` folder or how pip installed `mediapipe-silicon`?

**Comment by alifiya13** [comment]
I am facing the same issue with protobuf, did anyone found solution for it?

My System details:
Mac Air M1 2020
macOS Ventura 13.0.1
Protobuf 3.17.3

**Comment by cansik** [comment]
@alifiya13 Could you try to update to the following protobuf version: `pip install protobuf==3.20.1`?
